### ISSUE TITLE
请问肉神相同参数如何重载?

### ISSUE THREAD

**Issue by brooketang** [r0ysue/AndroidFridaBeginnersBook#2]
![$~9{5SH}UAS LD5@0RSX)MU](https://user-images.githubusercontent.com/22829077/131262277-4b85c686-5934-4449-aca0-aaf3eb72716a.png)

**Comment by chanalon** [comment]
填一下对应的参数就行了，比如，第一个你需要指定为 OooO00o.overload('java.lang.String')

**Comment by brooketang** [comment]
> 你需要指定为 OooO00o.overload('java.lang.String')

那第8个呢?也是 OooO00o.overload('java.lang.String')?两个没有冲突吗?我是试过这样写，没报错，但也没hook到。

**Comment by r0ysue** [comment]
用r0tracer
